### ISSUE TITLE
Empty Folders in source DC being synced as jsut values in destination DC

### ISSUE THREAD

**Issue by mynameisgv** [hashicorp/consul-replicate#40] opened 2016-05-02 03:08 UTC
Hello, 
I have couple of folders in one dc and i tried to sync with a destination dc, 
I see the folders that are not empty are being synced as folders and any folders that are empty are being synced as just keys. when I add something to the empty folder and sync, then it syncs as folder.But the previously created value still remains.

I am using consul-replicate v0.2.0

Thanks

**Comment by sethvargo** [comment] 2016-05-02 14:37
Duplicate of #25

**Closed** 2016-05-02 14:37 UTC
