### ISSUE TITLE
when folder 'xyz' is synced it is also creating a new key 'xyz'

### ISSUE THREAD

**Issue by kveerman** [hashicorp/consul-replicate#25] opened 2015-08-31 12:43 UTC
just tried out to sync a folder from dc2 to dc1 called 'xyz'
After sync was ready it also creates a new key 'xyz' in the kv store on dc1.

Deleting that key and changing/adding some new keys in dc2 had no impact on restarting the sync. All the changes are synced properly.

So it seems to me that new key shouldn't be created

**Comment by sethvargo** [comment] 2015-08-31 13:56
Hi @kveerman 

Thank you for opening an issue. Can you please explain your situation a bit more please? I am having trouble following. You're saying CR created a key when it should have created a folder? Can you send the structure of the KV store in both DCs please?

**Comment by kveerman** [comment] 2015-08-31 14:15
it creates the folder. which is expected
but it also creates a key with the same name as the folder. which is unexpected

kv store on dc=test_front
[{"CreateIndex":1522,"ModifyIndex":1522,"LockIndex":0,"Key":"testfront","Flags":0,"Value":"ZnJvbnQ="},{"CreateIndex":6827,"ModifyIndex":6832,"LockIndex":0,"Key":"tstfolder/test1","Flags":0,"Value":"dGVzdDF2YWx1ZSBuZXd2YWx1ZQ=="},{"CreateIndex":6825,"ModifyIndex":6825,"LockIndex":0,"Key":"tstfolder/","Flags":0,"Value":null}]


./consul-replicate -prefix "tstfolder@test_front" -once -log-level=debug
2015/08/31 16:06:23 [INFO] (runner) creating new runner (once: true)
2015/08/31 16:06:23 [INFO] (runner) creating consul/api client
2015/08/31 16:06:23 [DEBUG] (runner) setting basic auth
2015/08/31 16:06:23 [INFO] (runner) creating Watcher
2015/08/31 16:06:23 [INFO] (runner) starting
2015/08/31 16:06:23 [INFO] (watcher) adding "storeKeyPrefix(tstfolder@test_front)"
2015/08/31 16:06:23 [DEBUG] (watcher) "storeKeyPrefix(tstfolder@test_front)" starting
2015/08/31 16:06:23 [DEBUG] (view) "storeKeyPrefix(tstfolder@test_front)" starting fetch
2015/08/31 16:06:23 [DEBUG] ("storeKeyPrefix(tstfolder@test_front)") querying Consul with &{Datacenter:test_front AllowStale:false RequireConsistent:false WaitIndex:0 WaitTime:1m0s Token:}
2015/08/31 16:06:23 [DEBUG] ("storeKeyPrefix(tstfolder@test_front)") Consul returned 2 key pairs
2015/08/31 16:06:23 [INFO] (view) "storeKeyPrefix(tstfolder@test_front)" received data from consul
2015/08/31 16:06:23 [INFO] (runner) quiescence timers starting
2015/08/31 16:06:23 [INFO] (runner) quiescence minTimer fired
2015/08/31 16:06:23 [INFO] (runner) running
2015/08/31 16:06:23 [DEBUG] (runner) updated key "tstfolder/test1"
2015/08/31 16:06:23 [DEBUG] (runner) updated key "tstfolder"
2015/08/31 16:06:23 [INFO] (runner) replicated 2 updates, 0 deletes


kv store on dc=test_back after sync
[{"CreateIndex":7290,"ModifyIndex":7290,"LockIndex":0,"Key":"service/consul-replicate/statuses/82318559e473ba5a9a5e6208e4066384","Flags":0,"Value":"ewogICJMYXN0UmVwbGljYXRlZCI6IDY4MzIsCiAgIlNvdXJjZSI6ICJ0c3Rmb2xkZXIiLAogICJEZXN0aW5hdGlvbiI6ICJ0c3Rmb2xkZXIiCn0="},{"CreateIndex":1456,"ModifyIndex":1456,"LockIndex":0,"Key":"testkey","Flags":0,"Value":"dGVzdHZhbHVlIGZvciB0ZXN0a2V5"},{"CreateIndex":7288,"ModifyIndex":7288,"LockIndex":0,"Key":"tstfolder/test1","Flags":0,"Value":"dGVzdDF2YWx1ZSBuZXd2YWx1ZQ=="},{"CreateIndex":7289,"ModifyIndex":7289,"LockIndex":0,"Key":"tstfolder","Flags":0,"Value":null}

**Comment by subchen** [comment] 2015-12-24 04:06
Yes, I also hit this issue. :(

**Comment by bhadrig** [comment] 2016-05-02 02:42
I am also seeing this issue. May i know if there is a fix for this?

**Comment by bhadrig** [comment] 2016-05-02 02:51
TEst

**Comment by mynameisgv** [comment] 2016-05-02 02:54
Test

**Comment by mynameisgv** [comment] 2016-05-02 02:55
I am also facing this issues. Is there a fix for this? Any empty folder from source is being synced as key in the destination.

**Comment by daveadams** [comment] 2016-05-07 21:09
The root cause is that the trailing slash was being stripped off the destination key path because the code used fileutils.Join() to build the destination KV path. #41 should fix this.

**Closed** 2016-05-08 19:47 UTC
